//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сесия_1.BasaDanih
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    

        public partial class bdMalashin : DbContext
        {
            static private bdMalashin _context;
            public bdMalashin()
                : base("name=bdMalashinEntities")
            {
            }
            static public bdMalashin BasaDanih()
            {
                if (_context == null)
                    _context = new bdMalashin();
                return _context;

            }


            protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ismerenie> Ismerenie { get; set; }
        public virtual DbSet<Kategoria> Kategoria { get; set; }
        public virtual DbSet<Polsavotel> Polsavotel { get; set; }
        public virtual DbSet<Postovshik> Postovshik { get; set; }
        public virtual DbSet<Proisvoditel> Proisvoditel { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<Sclad> Sclad { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Vxod> Vxod { get; set; }
    }
}
