//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сесия_1.BasaDanih
{
    using System;
    using System.Collections.Generic;
    
    public partial class Polsavotel
    {
        public int Code { get; set; }
        public string Familia { get; set; }
        public string Imya { get; set; }
        public string Ochestvo { get; set; }
        public int Vxod_Code { get; set; }
    
        public virtual Vxod Vxod { get; set; }
    }
}
