//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сесия_1.BasaDanih
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sclad
    {
        public string Artickl { get; set; }
        public string Naimenovanie { get; set; }
        public int Ismerenie_Code { get; set; }
        public int Stoimost { get; set; }
        public int Skidca_Maximum { get; set; }
        public int Proisvoditel_Code { get; set; }
        public int Postovshik_Code { get; set; }
        public int Kategoria_Code { get; set; }
        public int Skidca_Deistvoisha { get; set; }
        public int Kolichestvo { get; set; }
        public string Opisanie { get; set; }
        public string Isobrajenie { get; set; }
    
        public virtual Ismerenie Ismerenie { get; set; }
        public virtual Kategoria Kategoria { get; set; }
        public virtual Postovshik Postovshik { get; set; }
        public virtual Proisvoditel Proisvoditel { get; set; }
    }
}
