//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Сесия_1.BasaDanih
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vxod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vxod()
        {
            this.Polsavotel = new HashSet<Polsavotel>();
        }
    
        public int Vxod_Code { get; set; }
        public string Login { get; set; }
        public string Parole { get; set; }
        public int Role_Code { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Polsavotel> Polsavotel { get; set; }
        public virtual Role Role { get; set; }
    }
}
